import LoadingScreen from "@/components/LoadingScreen/LoadingScreen";
import MainLayout from "@/components/MainLayout/MainLayout";
import "@/globalStyles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // eslint-disable-next-line react/no-unknown-property
    <html lang="en" color-theme="dark">
      <body>
        <div className="root-layout">
          <MainLayout>{children}</MainLayout>
          <LoadingScreen></LoadingScreen>
        </div>
      </body>
    </html>
  );
}
